[metadata]
name = "Example Plugin"
id = "example-plugin"
version = "0.1.0"
description = "An example plugin for the plugin system"
authors = ["Ethan Hanlon"]

[main]
dependencies = [] # List of plugin IDs that this plugin depends on
entrypoint = "./lib/index.js" # The entrypoint file for the plugin
pages = ['ExamplePage']  # The list of routes to generate for this plugin
