[metadata]
name = "Example Plugin"
id = "example-plugin"
version = "0.1.0"
description = "An example plugin for the plugin system"
authors = ["Ethan Hanlon"]

[main]
dependencies = [] # List of plugin IDs that this plugin depends on
entrypoint = "./index.ts" # The entrypoint file for the plugin

[pages]
# List of pages that this plugin provides
# The key is the path to the page, and the value is the path to the file
# relative to the plugin's root directory
"/example-page" = "./pages/example-page.tsx"

